name: SPIFFE example - Init
on:
  workflow_dispatch:

jobs:
  uds-example:
    runs-on: ubuntu-latest
    services:
      spiffe-agent:
        image: ghcr.io/arndt-s/spiffe-github-actions-agent:main
        env:
          SPIFFE_ENDPOINT_SOCKET: /tmp/spiffe/workload.sock
        volumes:
          - /tmp/spiffe:/tmp/spiffe
    permissions:
      contents: read
      id-token: write
      packages: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: gh token claims
        run: echo ${{ secrets.GITHUB_TOKEN }} | jq -R 'split(".") | .[0],.[1] | @base64d | fromjson'

      - name: check permissions
        run: |
          ls -l /tmp/spiffe/
          id

      - name: Initialize SPIFFE
        id: init
        uses: arndt-s/spiffe-github-actions@main
        with:
          id-token: ${{ secrets.GITHUB_TOKEN }}
          spiffe-workload-endpoint: unix:/tmp/spiffe/workload.sock