name: SPIFFE example - SPIFFE Endpoint Socket
on:
  workflow_dispatch:

jobs:
  uds-example:
    runs-on: ubuntu-latest
    services:
      spiffe-agent:
        image: ghcr.io/arndt-s/spiffe-github-actions-agent:main
        env:
          SPIFFE_ENDPOINT_SOCKET: /spiffe/workload.sock
        volumes:
          - /spiffe:/spiffe
    permissions:
      contents: read
      id-token: write
      packages: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Initialize SPIFFE
        id: init
        uses: arndt-s/spiffe-github-actions@main
        with:
          action: 'init'

      - name: Get JWT SVID
        id: fetch-jwt-svid
        uses: arndt-s/spiffe-github-actions@main
        with:
          action: 'fetch-jwt-svid'

      - name: Print JWT SVID
        run: echo ${{ steps.fetch-jwt-svid.outputs.jwt_svid }}

      - name: Print JWT SVID claims
        run: echo ${{ steps.fetch-jwt-svid.outputs.jwt_svid }} | jq -R 'split(".") | .[0],.[1] | @base64d | fromjson'