name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: read
    steps:
      - name: Print variables
        shell: bash
        run: |
          echo $ACTIONS_ID_TOKEN_REQUEST_URL
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN